spring:
  application:
    name: user-service
  cloud:
    aws:
      dynamodb:
        region: ${SPRING_CLOUD_AWS_DYNAMODB_REGION:local}
      credentials:
        access-key: ${SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY:fake}
        secret-key: ${SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY:fake}
  grpc:
    server:
      reflection:
        enabled: ${SPRING_GRPC_SERVER_REFLECTION_ENABLED:true}
      ssl:
        secure: ${SPRING_GRPC_SERVER_SSL_SECURE:false}

aws:
  region: ${AWS_REGION:local}
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:http://localhost:8000}
    accessKey: ${AWS_DYNAMODB_ACCESS_KEY:fake}
    secretKey: ${AWS_DYNAMODB_SECRET_KEY:fake}
  dynamo:
    sessionToken: ${AWS_DYNAMO_SESSION_TOKEN:fake-token}

grpc:
  server:
    port: 9093
    reflection-service-enabled: true
    
minio:
  url: http://localhost:9000
  access:
    name: minio
    secret: password
  bucket:
    name: stardew-valley-clicker