spring:
  cloud:
    aws:
      dynamodb:
        region: local
      credentials:
        access-key: fake
        secret-key: fake
  grpc:
    server:
      reflection:
        enabled: true
      ssl:
        secure: false
  data:
    redis:
      port: 6379
      host: localhost

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

aws:
  region: local
  dynamodb:
    endpoint: http://localhost:8000
    accessKey: fake
    secretKey: fake
  dynamo:
    sessionToken: fake-token