receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      memory:
      load:

processors:
  batch:
  attributes/client_address:
    actions:
      - key: client.address
        action: delete
  memory_limiter:
    check_interval: 1s
    limit_mib: 6000
    spike_limit_mib: 1200

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      processors: [memory_limiter, batch, attributes/client_address]
      exporters: [otlp]
    metrics:
      processors: [memory_limiter]
      exporters: [prometheus]
    logs:
      processors: [memory_limiter, batch]