{
 "title": "Java Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Threads",
   "type": "stat",
   "description": "The number of events processed.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_usage_after_gc_percent"
    }
   ]
  },
  {
   "title": "HTTP request Timeline",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "dls_springboot_telemetry_http_event_processing_time_seconds"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "description": "The number of HTTP request received",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dls_springboot_telemetry_http_event_processed_count_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}